services:
  nuxt:
    build: .
    command: npm run dev
    env_file:
      - .env
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=nuxt.arcjet-examples.orb.local
    labels:
      - dev.orbstack.domains=nuxt.arcjet-examples.orb.local
    ports:
      - 3000
    volumes:
      - .:/app
      - nuxt_node_modules:/app/node_modules

volumes:
  nuxt_node_modules:
