services:
  gatsby:
    build: .
    command: npm run develop
    env_file:
      - .env.local
    labels:
      - dev.orbstack.domains=gatsby.arcjet-examples.orb.local
    ports:
      - 8000
    volumes:
      - .:/app
      - gatsby_node_modules:/app/node_modules

volumes:
  gatsby_node_modules:
