services:
  astro:
    build: .
    command: npm run dev
    env_file:
      - .env.local
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=astro.arcjet-examples.orb.local
    labels:
      - dev.orbstack.domains=astro.arcjet-examples.orb.local
    ports:
      - 4321
    volumes:
      - .:/app
      - astro_node_modules:/app/node_modules

volumes:
  astro_node_modules: