# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: proto/api/v1/remote_rules.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import proto.api.v1.remote_rules_pb2 as proto_dot_api_dot_v1_dot_remote__rules__pb2


class RemoteRulesService(Protocol):
    async def create_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_remote_rules(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RemoteRulesServiceASGIApplication(ConnectASGIApplication[RemoteRulesService]):
    def __init__(self, service: RemoteRulesService | AsyncGenerator[RemoteRulesService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/proto.api.v1.RemoteRulesService/CreateRemoteRule": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_remote_rule,
                ),
                "/proto.api.v1.RemoteRulesService/GetRemoteRule": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_remote_rule,
                ),
                "/proto.api.v1.RemoteRulesService/ListRemoteRules": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRemoteRules",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_remote_rules,
                ),
                "/proto.api.v1.RemoteRulesService/UpdateRemoteRule": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_remote_rule,
                ),
                "/proto.api.v1.RemoteRulesService/DeleteRemoteRule": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_remote_rule,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/proto.api.v1.RemoteRulesService"


class RemoteRulesServiceClient(ConnectClient):
    async def create_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_remote_rules(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRemoteRules",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class RemoteRulesServiceSync(Protocol):
    def create_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_remote_rules(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_remote_rule(self, request: proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest, ctx: RequestContext) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RemoteRulesServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: RemoteRulesServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/proto.api.v1.RemoteRulesService/CreateRemoteRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_remote_rule,
                ),
                "/proto.api.v1.RemoteRulesService/GetRemoteRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_remote_rule,
                ),
                "/proto.api.v1.RemoteRulesService/ListRemoteRules": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRemoteRules",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_remote_rules,
                ),
                "/proto.api.v1.RemoteRulesService/UpdateRemoteRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_remote_rule,
                ),
                "/proto.api.v1.RemoteRulesService/DeleteRemoteRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteRemoteRule",
                        service_name="proto.api.v1.RemoteRulesService",
                        input=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest,
                        output=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_remote_rule,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/proto.api.v1.RemoteRulesService"


class RemoteRulesServiceClientSync(ConnectClientSync):
    def create_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.CreateRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.GetRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_remote_rules(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRemoteRules",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.ListRemoteRulesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.UpdateRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_remote_rule(
        self,
        request: proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRemoteRule",
                service_name="proto.api.v1.RemoteRulesService",
                input=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleRequest,
                output=proto_dot_api_dot_v1_dot_remote__rules__pb2.DeleteRemoteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
