services:
  fastify:
    build: .
    command: npm run dev
    env_file:
      - .env
    labels:
      - dev.orbstack.domains=fastify.arcjet-examples.orb.local
    ports:
      - 3000
    volumes:
      - .:/app
      - fastify_node_modules:/app/node_modules

volumes:
  fastify_node_modules:
