services:
  nextjs-form:
    build: .
    command: npm run dev
    labels:
      - dev.orbstack.domains=nextjs-form.arcjet-examples.orb.local
    env_file:
      - .env.local
    ports:
      - 3000
    volumes:
      - .:/app
      - nextjs-form_node_modules:/app/node_modules

volumes:
  nextjs-form_node_modules:
