services:
  nextjs:
    build: .
    command: npm run dev
    labels:
      - dev.orbstack.domains=nextjs.arcjet-examples.orb.local
    env_file:
      - .env.local
    ports:
      - 3000
    volumes:
      - .:/app
      - nextjs_node_modules:/app/node_modules

volumes:
  nextjs_node_modules:
